# DB
spring.jpa.properties.hibernate.format_sql=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.sql.init.mode=
spring.jpa.defer-datasource-initialization=

# App Config
app.data-seeder.admin.email=
app.data-seeder.admin.password=
app.mail.from=
app.frontend.url=

# Google Books API
googlebooks.api.key=

# SMTP connection
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.starttls.required=

mailtrap.api.key=

# JWT Authentication
api.security.token.secret=

# Swagger
# springdoc.api-docs.enabled=true
# springdoc.swagger-ui.enabled=true